# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_pat', models.CharField(max_length=50)),
                ('apellido_mat', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.TextField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Carrera', verbose_name='diagn\xf3stico Carrera')),
            ],
        ),
    ]
